from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class InnerTubeCommand(BaseModel):
    apiPath: str
    payload: dict = Field(default_factory=dict)


class Thumbnail(BaseModel):
    url: str
    width: Optional[int] = None
    height: Optional[int] = None


class VideoItem(BaseModel):
    id: str
    title: str
    channel: Optional[str] = None
    viewCountText: Optional[str] = None
    publishedTimeText: Optional[str] = None
    durationText: Optional[str] = None
    thumbnails: List[Thumbnail] = Field(default_factory=list)
    playlistSetVideoId: Optional[str] = None
    playlistIndexText: Optional[str] = None
    playlistSelected: Optional[bool] = None
    playlistCanRemove: bool = False
    playlistCanMoveToTop: bool = False
    playlistCanMoveToBottom: bool = False


class RecommendationsResponse(BaseModel):
    items: List[VideoItem] = Field(default_factory=list)
    continuation: Optional[str] = None
    note: Optional[str] = None


class StreamInfo(BaseModel):
    url: str
    formatId: Optional[str] = None
    mimeType: Optional[str] = None
    qualityLabel: Optional[str] = None
    httpHeaders: dict[str, str] = Field(default_factory=dict)
    bitrate: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    fps: Optional[int] = None
    audioChannels: Optional[int] = None
    audioCodec: Optional[str] = None
    videoCodec: Optional[str] = None
    container: Optional[str] = None
    hasAudio: bool = False
    hasVideo: bool = False
    isAdaptive: bool = False
    streamKind: str = "muxed"


class SubtitleTrack(BaseModel):
    language: str
    label: str
    url: str
    isAutoGenerated: bool


class CommentItem(BaseModel):
    id: str
    author: str
    avatarUrl: Optional[str] = None
    body: str
    likeCountText: Optional[str] = None
    publishedTimeText: Optional[str] = None
    replyCountText: Optional[str] = None
    pinnedText: Optional[str] = None


class CommentsResponse(BaseModel):
    comments: List[CommentItem] = Field(default_factory=list)
    commentCountText: Optional[str] = None
    continuation: Optional[str] = None


class SubscriptionState(BaseModel):
    channelId: str
    buttonText: Optional[str] = None
    subscribed: bool = False
    enabled: bool = False
    subscriberCountText: Optional[str] = None


class RatingState(BaseModel):
    status: str = "INDIFFERENT"
    likeCountText: Optional[str] = None


class PlaylistOption(BaseModel):
    playlistId: str
    title: str
    privacy: Optional[str] = None
    containsSelectedVideos: str = "NONE"
    saved: bool = False


class PlaylistSummary(BaseModel):
    playlistId: str
    title: str
    privacy: Optional[str] = None
    itemCountText: Optional[str] = None
    updatedText: Optional[str] = None
    thumbnails: List[Thumbnail] = Field(default_factory=list)


class PlaylistFeed(BaseModel):
    playlistId: str
    title: str
    ownerText: Optional[str] = None
    privacy: Optional[str] = None
    itemCountText: Optional[str] = None
    items: List[VideoItem] = Field(default_factory=list)
    continuation: Optional[str] = None


class VideoPlayback(BaseModel):
    id: str
    title: Optional[str] = None
    channel: Optional[str] = None
    channelId: Optional[str] = None
    channelAvatarUrl: Optional[str] = None
    subscriberCountText: Optional[str] = None
    viewCountText: Optional[str] = None
    publishedTimeText: Optional[str] = None
    publishedDateText: Optional[str] = None
    likeCountText: Optional[str] = None
    durationText: Optional[str] = None
    description: Optional[str] = None
    commentCountText: Optional[str] = None
    streams: List[StreamInfo] = Field(default_factory=list)
    recommendations: List[VideoItem] = Field(default_factory=list)
    comments: List[CommentItem] = Field(default_factory=list)
    playbackStrategy: str = "direct"
    preferredManifestStream: Optional[StreamInfo] = None
    preferredMuxedStream: Optional[StreamInfo] = None
    preferredVideoStream: Optional[StreamInfo] = None
    preferredAudioStream: Optional[StreamInfo] = None
    bestStreamUrl: Optional[str] = None
    bestStream: Optional[StreamInfo] = None
    subtitles: List[SubtitleTrack] = Field(default_factory=list)
    storyboard: Optional["StoryboardSpec"] = None
    subscription: Optional[SubscriptionState] = None
    rating: Optional[RatingState] = None
    watchLater: Optional[PlaylistOption] = None
    playlistSaveEnabled: bool = False
    recommendationsContinuation: Optional[str] = None


class SearchResponse(BaseModel):
    items: List[VideoItem] = Field(default_factory=list)
    continuation: Optional[str] = None
    query: str = ""


class AuthStatusResponse(BaseModel):
    authenticated: bool = False
    browser: Optional[str] = None
    browserLabel: Optional[str] = None
    message: Optional[str] = None


class BrowserAuthRequest(BaseModel):
    browser: str


class RatingRequest(BaseModel):
    action: str


class SubscriptionRequest(BaseModel):
    subscribed: bool


class WatchLaterRequest(BaseModel):
    saved: bool


class PlaylistMutationRequest(BaseModel):
    playlistId: str
    saved: bool


class PlaylistItemMutationRequest(BaseModel):
    setVideoId: str


class PlaylistItemReorderRequest(BaseModel):
    setVideoId: str
    position: str


class PlaylistOptionsResponse(BaseModel):
    options: List[PlaylistOption] = Field(default_factory=list)


class PlaylistLibraryResponse(BaseModel):
    items: List[PlaylistSummary] = Field(default_factory=list)
    continuation: Optional[str] = None


class SubscriptionResponse(BaseModel):
    subscription: Optional[SubscriptionState] = None


class RatingResponse(BaseModel):
    rating: Optional[RatingState] = None


class WatchLaterResponse(BaseModel):
    watchLater: Optional[PlaylistOption] = None


class PlaylistMutationResponse(BaseModel):
    playlist: Optional[PlaylistOption] = None


class PlaylistItemMutationResponse(BaseModel):
    success: bool = True


class StoryboardSpec(BaseModel):
    """Storyboard sprite-sheet spec for scrub preview thumbnails."""
    urls: List[str]           # one URL per sprite-sheet file (indexed by file number)
    tileWidth: int            # width of a single thumbnail tile in pixels
    tileHeight: int           # height of a single thumbnail tile in pixels
    cols: int                 # columns of tiles per sprite sheet
    rows: int                 # rows of tiles per sprite sheet
    intervalSeconds: float    # seconds between consecutive frames
