import Foundation

struct Thumbnail: Codable, Hashable, Sendable {
    let url: String
    let width: Int?
    let height: Int?
}

struct VideoItem: Codable, Identifiable, Hashable, Sendable {
    let id: String
    let title: String
    let channel: String?
    let viewCountText: String?
    let publishedTimeText: String?
    let durationText: String?
    let thumbnails: [Thumbnail]

    var thumbnailURL: URL? {
        guard let urlString = thumbnails.last?.url else { return nil }
        return URL(string: urlString)
    }
}

struct RecommendationsResponse: Codable, Sendable {
    let items: [VideoItem]
    let continuation: String?
    let note: String?
}

struct SearchResponse: Codable, Sendable {
    let items: [VideoItem]
    let continuation: String?
    let query: String
}

struct StreamInfo: Codable, Hashable, Sendable {
    let url: String
    let formatId: String?
    let mimeType: String?
    let qualityLabel: String?
    let httpHeaders: [String: String]?
    let bitrate: Int?
    let width: Int?
    let height: Int?
    let fps: Int?
    let audioChannels: Int?
    let audioCodec: String?
    let videoCodec: String?
    let container: String?
    let hasAudio: Bool
    let hasVideo: Bool
    let isAdaptive: Bool
    let streamKind: String
}

struct CommentItem: Codable, Hashable, Identifiable, Sendable {
    let id: String
    let author: String
    let avatarUrl: String?
    let body: String
    let likeCountText: String?
    let publishedTimeText: String?
    let replyCountText: String?
    let pinnedText: String?

    var avatarURL: URL? {
        guard let avatarUrl else { return nil }
        return URL(string: avatarUrl)
    }
}

struct CommentsResponse: Codable, Sendable {
    let comments: [CommentItem]
    let commentCountText: String?
}

struct StoryboardSpec: Codable, Sendable {
    let urls: [String]           // one URL per sprite-sheet file (file index = array index)
    let tileWidth: Int
    let tileHeight: Int
    let cols: Int
    let rows: Int
    let intervalSeconds: Double

    /// Returns the sprite-sheet URL, column, and row for the tile that covers `seconds`.
    func tileInfo(at seconds: Double) -> (url: URL, col: Int, row: Int)? {
        guard intervalSeconds > 0, cols > 0, rows > 0, !urls.isEmpty else { return nil }
        let frameIndex = Int(seconds / intervalSeconds)
        let framesPerFile = cols * rows
        let fileIndex = frameIndex / framesPerFile
        guard fileIndex < urls.count else { return nil }
        let posInFile = frameIndex % framesPerFile
        guard let url = URL(string: urls[fileIndex]) else { return nil }
        return (url, posInFile % cols, posInFile / cols)
    }
}

struct SubtitleTrack: Codable, Hashable, Sendable {
    let language: String
    let label: String
    let url: String
    let isAutoGenerated: Bool
}

struct SubscriptionState: Codable, Hashable, Sendable {
    let channelId: String
    let buttonText: String?
    let subscribed: Bool
    let enabled: Bool
    let subscriberCountText: String?
}

struct RatingState: Codable, Hashable, Sendable {
    let status: String
    let likeCountText: String?
}

struct PlaylistOption: Codable, Hashable, Identifiable, Sendable {
    let playlistId: String
    let title: String
    let privacy: String?
    let containsSelectedVideos: String
    let saved: Bool

    var id: String { playlistId }
}

struct VideoPlayback: Codable, Sendable {
    let id: String
    let title: String?
    let channel: String?
    let channelId: String?
    let channelAvatarUrl: String?
    let subscriberCountText: String?
    let viewCountText: String?
    let publishedTimeText: String?
    let publishedDateText: String?
    let likeCountText: String?
    let durationText: String?
    let description: String?
    let commentCountText: String?
    let streams: [StreamInfo]
    let recommendations: [VideoItem]
    let comments: [CommentItem]
    let playbackStrategy: String
    let preferredManifestStream: StreamInfo?
    let preferredMuxedStream: StreamInfo?
    let preferredVideoStream: StreamInfo?
    let preferredAudioStream: StreamInfo?
    let bestStreamUrl: String?
    let bestStream: StreamInfo?
    let subtitles: [SubtitleTrack]?
    let storyboard: StoryboardSpec?
    let subscription: SubscriptionState?
    let rating: RatingState?
    let watchLater: PlaylistOption?
    let playlistSaveEnabled: Bool

    var channelAvatarURL: URL? {
        guard let channelAvatarUrl else { return nil }
        return URL(string: channelAvatarUrl)
    }

    func with(
        subscriberCountText: String? = nil,
        likeCountText: String? = nil,
        subscription: SubscriptionState? = nil,
        rating: RatingState? = nil,
        watchLater: PlaylistOption? = nil
    ) -> VideoPlayback {
        VideoPlayback(
            id: id,
            title: title,
            channel: channel,
            channelId: channelId,
            channelAvatarUrl: channelAvatarUrl,
            subscriberCountText: subscriberCountText ?? self.subscriberCountText,
            viewCountText: viewCountText,
            publishedTimeText: publishedTimeText,
            publishedDateText: publishedDateText,
            likeCountText: likeCountText ?? self.likeCountText,
            durationText: durationText,
            description: description,
            commentCountText: commentCountText,
            streams: streams,
            recommendations: recommendations,
            comments: comments,
            playbackStrategy: playbackStrategy,
            preferredManifestStream: preferredManifestStream,
            preferredMuxedStream: preferredMuxedStream,
            preferredVideoStream: preferredVideoStream,
            preferredAudioStream: preferredAudioStream,
            bestStreamUrl: bestStreamUrl,
            bestStream: bestStream,
            subtitles: subtitles,
            storyboard: storyboard,
            subscription: subscription ?? self.subscription,
            rating: rating ?? self.rating,
            watchLater: watchLater ?? self.watchLater,
            playlistSaveEnabled: playlistSaveEnabled
        )
    }
}

struct AuthStatusResponse: Codable, Equatable, Sendable {
    let authenticated: Bool
    let browser: String?
    let browserLabel: String?
    let message: String?

    static let signedOut = AuthStatusResponse(
        authenticated: false,
        browser: nil,
        browserLabel: nil,
        message: nil
    )
}

struct PlaylistOptionsResponse: Codable, Sendable {
    let options: [PlaylistOption]
}

struct SubscriptionResponse: Codable, Sendable {
    let subscription: SubscriptionState?
}

struct RatingResponse: Codable, Sendable {
    let rating: RatingState?
}

struct WatchLaterResponse: Codable, Sendable {
    let watchLater: PlaylistOption?
}

struct PlaylistMutationResponse: Codable, Sendable {
    let playlist: PlaylistOption?
}
